// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TDEvalutaion.Models.EntityFramework;

#nullable disable

namespace TDEvalutaion.Migrations
{
    [DbContext(typeof(TDEvaluationDBContext))]
    [Migration("20240220172542_CreationBDFruitsPaniers")]
    partial class CreationBDFruitsPaniers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TDEvalutaion.Models.EntityFramework.Fruit", b =>
                {
                    b.Property<int>("IdFruit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idfruit");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFruit"));

                    b.Property<string>("NomFruit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nomfruit");

                    b.Property<int>("PoidsFruit")
                        .HasColumnType("integer")
                        .HasColumnName("poidsfruit");

                    b.HasKey("IdFruit");

                    b.ToTable("fruit");
                });

            modelBuilder.Entity("TDEvalutaion.Models.EntityFramework.Panier", b =>
                {
                    b.Property<int>("IdPanier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idpanier");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPanier"));

                    b.Property<int>("IdFruit")
                        .HasColumnType("integer")
                        .HasColumnName("idfruit");

                    b.Property<int>("Quantitepanier")
                        .HasColumnType("integer")
                        .HasColumnName("quantitepanier");

                    b.HasKey("IdPanier")
                        .HasName("pk_panier");

                    b.HasIndex("IdFruit");

                    b.ToTable("panier");
                });

            modelBuilder.Entity("TDEvalutaion.Models.EntityFramework.Panier", b =>
                {
                    b.HasOne("TDEvalutaion.Models.EntityFramework.Fruit", "FruitDuPanier")
                        .WithMany("PanierDuFruit")
                        .HasForeignKey("IdFruit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pan_frt");

                    b.Navigation("FruitDuPanier");
                });

            modelBuilder.Entity("TDEvalutaion.Models.EntityFramework.Fruit", b =>
                {
                    b.Navigation("PanierDuFruit");
                });
#pragma warning restore 612, 618
        }
    }
}
